# @package _global_
config: abmusu

batch_size: 1
epoch: 100
report_freq: 1
accumulate_step: 8
margin: 0.001
gold_margin: 0
gold_weight: 0
mle_weight: 0.1
rank_weight: 10
model_type: VietAI/vit5-base-vietnews-summarization
warmup_steps: 125
normalize: true
grad_norm: 0
seed: 970903
no_gold: false
pretrained:
max_lr: 2e-3
scale: 1
score_mode: log
datatype: diverse
dataset: abmusu
max_summ_len: 120 # do not use for training
max_candidates: 16
smooth: 0.1
max_doc_len: 4096
length_penalty: 1.0
do_generate: true
gen_max_len: 500
gen_min_len: 200
is_pegasus: false
is_t5: true
adding: 0
eval_interval: 100
num_beams: 1
fp16: true
train_split: train
val_split: val